## Tomcat
#server:
#  port: 9209
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.79.253.201:7706/yihuoban?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#    username: yhbpro
#    password: aedc#;08zEur}zT
#
#jimmer:
#  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
#  show-sql: on
#  pretty-sql: true
#  foreign-key-enabled-by-default: false
#  database-validation:
#    mode: ERROR
#    schema: yihuoban